import type { MultiStepProblem } from './problemSets';

const OPENSTAX =
  'Adapted from OpenStax University Physics Volume 1 (CC BY 4.0), https://openstax.org/books/university-physics-volume-1';

/** College-level homework / class problem-solving items, keyed by existing set id. */
export const homeworkBySet: Record<string, MultiStepProblem[]> = {
  'graphs-1d': [
    {
      id: 'hw-kg-1',
      kind: 'multistep',
      title: 'Three-stage cart on a line',
      stem:
        'A cart starts from rest and moves in a straight line through three successive stages: it accelerates at $a = +2.0\\,\\mathrm{m/s}^2$ for $4.0\\,\\mathrm{s}$, then travels at constant velocity for $6.0\\,\\mathrm{s}$, then brakes at $a = -3.0\\,\\mathrm{m/s}^2$ until it stops. Take $x = 0$ at $t = 0$. Use $g$ only if you need it (you should not).',
      figure: 'two-stage-motion',
      source: {
        credit: 'Original SN1 homework (standard piecewise-kinematics structure).',
      },
      simSlug: 'kinematics-graphs',
      parts: [
        {
          id: 'hw-kg-1a',
          prompt: '(a) Speed at the end of the acceleration stage.',
          kind: 'numeric',
          answer: 8,
          tolerance: 0.08,
          units: 'm/s',
          hint: '$v = v_0 + at$ from rest.',
          solution: '$v = 0 + (2.0)(4.0) = 8.0\\,\\mathrm{m/s}$. This is also the cruise speed.',
        },
        {
          id: 'hw-kg-1b',
          prompt: '(b) Displacement during the $4.0\\,\\mathrm{s}$ acceleration.',
          kind: 'numeric',
          answer: 16,
          tolerance: 0.12,
          units: 'm',
          hint: 'From rest, $\\Delta x = \\tfrac{1}{2}at^2$, or the triangle under $v$–$t$.',
          solution: '$\\Delta x_1 = \\tfrac{1}{2}(2.0)(4.0)^2 = 16\\,\\mathrm{m}$.',
        },
        {
          id: 'hw-kg-1c',
          prompt: '(c) Displacement during the $6.0\\,\\mathrm{s}$ cruise.',
          kind: 'numeric',
          answer: 48,
          tolerance: 0.2,
          units: 'm',
          hint: 'Constant $v$ from (a).',
          solution: '$\\Delta x_2 = (8.0)(6.0) = 48\\,\\mathrm{m}$.',
        },
        {
          id: 'hw-kg-1d',
          prompt: '(d) Time spent braking to a stop.',
          kind: 'numeric',
          answer: 2.67,
          tolerance: 0.08,
          units: 's',
          hint: '$0 = 8.0 + (-3.0)t_3$.',
          solution: '$t_3 = 8.0/3.0 = 2.67\\,\\mathrm{s}$.',
        },
        {
          id: 'hw-kg-1e',
          prompt: '(e) Total displacement from start until rest.',
          kind: 'numeric',
          answer: 74.7,
          tolerance: 0.4,
          units: 'm',
          hint: 'Add three segments. Braking: $v^2 = v_0^2 + 2a\\Delta x$.',
          solution:
            '$\\Delta x_3 = (0 - 8.0^2)/(2(-3.0)) = 10.67\\,\\mathrm{m}$. Total $16 + 48 + 10.67 = 74.7\\,\\mathrm{m}$.',
          simSlug: 'kinematics-graphs',
          simParams: { profile: 'cruise', tCursor: 5 },
        },
      ],
    },
  ],
  'instant-v': [
    {
      id: 'hw-iv-1',
      kind: 'multistep',
      title: 'Particle with a quadratic $x(t)$',
      stem:
        'A particle moves on the $x$-axis with $x(t) = 4t - t^2$ (metres, seconds) on $0 \\le t \\le 5\\,\\mathrm{s}$. The figure is a sketch of that parabola, not a fitted data plot.',
      figure: 'x-t-particle',
      source: {
        credit: 'Original SN1 (calculus definition of $v$ and $a$ on a given $x(t)$).',
      },
      simSlug: 'instantaneous-velocity',
      parts: [
        {
          id: 'hw-iv-1a',
          prompt: '(a) Instantaneous velocity at $t = 1.0\\,\\mathrm{s}$.',
          kind: 'numeric',
          answer: 2,
          tolerance: 0.06,
          units: 'm/s',
          hint: '$v = dx/dt = 4 - 2t$.',
          solution: '$v(1) = 4 - 2 = 2.0\\,\\mathrm{m/s}$ (tangent slope).',
          simSlug: 'instantaneous-velocity',
          simParams: { x0: 0, v0: 4, a: -2, t1: 1, dt: 0.4, tMax: 5 },
        },
        {
          id: 'hw-iv-1b',
          prompt: '(b) Time at which the particle is instantaneously at rest.',
          kind: 'numeric',
          answer: 2,
          tolerance: 0.06,
          units: 's',
          hint: 'Set $v(t) = 0$.',
          solution: '$4 - 2t = 0 \\Rightarrow t = 2.0\\,\\mathrm{s}$. The $x$–$t$ graph has a horizontal tangent there.',
        },
        {
          id: 'hw-iv-1c',
          prompt: '(c) Acceleration (constant on this interval).',
          kind: 'numeric',
          answer: -2,
          tolerance: 0.06,
          units: 'm/s²',
          hint: '$a = dv/dt$.',
          solution: '$a = -2.0\\,\\mathrm{m/s}^2$ at every instant on the given interval.',
        },
        {
          id: 'hw-iv-1d',
          prompt: '(d) Average velocity on $[0, 2.0]\\,\\mathrm{s}$.',
          kind: 'numeric',
          answer: 2,
          tolerance: 0.08,
          units: 'm/s',
          hint: '$v_\\mathrm{avg} = [x(2)-x(0)]/\\Delta t$. Compare with the secant.',
          solution:
            '$x(2) = 8 - 4 = 4\\,\\mathrm{m}$, $x(0) = 0$, so $v_\\mathrm{avg} = 2.0\\,\\mathrm{m/s}$. Equal to $v(1)$ here because $v(t)$ is linear.',
          simSlug: 'instantaneous-velocity',
          simParams: { x0: 0, v0: 4, a: -2, t1: 1, dt: 2, tMax: 5 },
        },
      ],
    },
  ],
  circular: [
    {
      id: 'hw-cm-1',
      kind: 'multistep',
      title: 'Car over a circular crest',
      stem:
        'An $800\\,\\mathrm{kg}$ car passes the crest of a hill that can be modelled as an arc of a vertical circle of radius $R = 50\\,\\mathrm{m}$. At the crest the speed is $v = 16\\,\\mathrm{m/s}$. Take $g = 9.80\\,\\mathrm{m/s}^2$, and take the car as a particle. The normal force $\\vec{n}$ is from the road on the car.',
      figure: 'hill-crest',
      source: {
        credit: OPENSTAX + '. Treatment follows Example 6.9 (apparent weight at a crest).',
        url: 'https://openstax.org/books/university-physics-volume-1/pages/6-3-centripetal-force',
      },
      simSlug: 'circular-motion',
      relatedCheckNote:
        'Related check: open the simulation to compare radial acceleration $a_r = v^2/R$ on a horizontal circle (the crest figure is a paper problem). The canvas radius is not $50\\,\\mathrm{m}$, so the $a_r$ readout will not equal the paper answer $5.12\\,\\mathrm{m/s}^2$.',
      simButtonLabel: 'Related check: compare $a_r$',
      parts: [
        {
          id: 'hw-cm-1a',
          prompt: '(a) Magnitude of the centripetal acceleration at the crest.',
          kind: 'numeric',
          answer: 5.12,
          tolerance: 0.1,
          units: 'm/s²',
          hint: '$a_r = v^2/R$ toward the centre (downward at the crest).',
          solution: '$a_r = (16)^2/50 = 5.12\\,\\mathrm{m/s}^2$.',
          simSlug: 'circular-motion',
          simParams: { R: 5, w0: 3.2, alpha: 0 },
          relatedCheckNote:
            'Related check: open the simulation to compare radial acceleration $a_r$ (scaled horizontal circle; the crest figure is a paper problem). The canvas radius is not $50\\,\\mathrm{m}$, so the $a_r$ readout will not equal the paper answer.',
          simButtonLabel: 'Related check: compare $a_r$',
        },
        {
          id: 'hw-cm-1b',
          prompt: '(b) Magnitude of the normal force at the crest.',
          kind: 'numeric',
          answer: 3740,
          tolerance: 40,
          units: 'N',
          hint: 'Downward positive toward the centre: $mg - n = m v^2/R$.',
          solution:
            '$n = m(g - v^2/R) = 800(9.80 - 5.12) = 3.74\\times 10^3\\,\\mathrm{N}$. Apparent weight is less than $mg$.',
        },
        {
          id: 'hw-cm-1c',
          prompt: '(c) Fastest speed at the crest for which the car just stays in contact ($n \\to 0$).',
          kind: 'numeric',
          answer: 22.1,
          tolerance: 0.3,
          units: 'm/s',
          hint: '$mg = m v_\\mathrm{max}^2/R$.',
          solution: '$v_\\mathrm{max} = \\sqrt{gR} = \\sqrt{9.80\\times 50} = 22.1\\,\\mathrm{m/s}$.',
        },
        {
          id: 'hw-cm-1d',
          prompt: '(d) At the crest, compared with the car’s true weight $mg$, the normal force is',
          kind: 'choice',
          answer: 'smaller',
          choices: [
            { id: 'equal', label: 'equal, because the road still supports the car' },
            { id: 'larger', label: 'larger; you feel heavier at the top of a hill' },
            { id: 'smaller', label: 'smaller; $n = m(g - v^2/R)$' },
            { id: 'zero', label: 'zero for any $v > 0$' },
          ],
          hint: 'UCM in a vertical circle still needs a net downward force at the top.',
          solution:
            'Smaller. Part of $mg$ supplies $mv^2/R$. You feel lighter at the crest (and heavier in a dip).',
        },
      ],
    },
  ],
  'rot-kin': [
    {
      id: 'hw-rk-1',
      kind: 'multistep',
      title: 'Flywheel: graphs, then UCM vs non-UCM at the rim',
      stem:
        'A flywheel of radius $R = 0.25\\,\\mathrm{m}$ rotates about a fixed axis. It starts from rest and has constant angular acceleration $\\alpha = 3.0\\,\\mathrm{rad/s}^2$. Consider a paint mark $P$ on the rim. Use $t = 2.0\\,\\mathrm{s}$ unless a part says otherwise.',
      figure: 'flywheel-rim',
      source: {
        credit: OPENSTAX + '. Combines §10.1–10.2 rotational kinematics with $a_r$ and $a_t$ at a rim point.',
        url: 'https://openstax.org/books/university-physics-volume-1/pages/10-1-rotational-variables',
      },
      simSlug: 'rotational-kinematics',
      parts: [
        {
          id: 'hw-rk-1a',
          prompt: '(a) Angular velocity at $t = 2.0\\,\\mathrm{s}$.',
          kind: 'numeric',
          answer: 6,
          tolerance: 0.08,
          units: 'rad/s',
          hint: '$\\omega = \\omega_0 + \\alpha t$.',
          solution: '$\\omega = 0 + (3.0)(2.0) = 6.0\\,\\mathrm{rad/s}$.',
          simSlug: 'rotational-kinematics',
          simParams: { profile: 'const-alpha', alpha: 3, w0: 0, R: 0.25, tCursor: 2 },
        },
        {
          id: 'hw-rk-1b',
          prompt: '(b) Angular displacement from $t = 0$ to $2.0\\,\\mathrm{s}$.',
          kind: 'numeric',
          answer: 6,
          tolerance: 0.1,
          units: 'rad',
          hint: '$\\theta = \\tfrac{1}{2}\\alpha t^2$, or the area under $\\omega$–$t$.',
          solution: '$\\theta = \\tfrac{1}{2}(3.0)(4.0) = 6.0\\,\\mathrm{rad}$ (unwrapped).',
        },
        {
          id: 'hw-rk-1c',
          prompt: '(c) Tangential speed of $P$ at $t = 2.0\\,\\mathrm{s}$.',
          kind: 'numeric',
          answer: 1.5,
          tolerance: 0.05,
          units: 'm/s',
          hint: '$v_t = \\omega R$.',
          solution: '$v_t = (6.0)(0.25) = 1.50\\,\\mathrm{m/s}$.',
        },
        {
          id: 'hw-rk-1d',
          prompt: '(d) Tangential acceleration of $P$.',
          kind: 'numeric',
          answer: 0.75,
          tolerance: 0.04,
          units: 'm/s²',
          hint: '$a_t = \\alpha R$. Independent of $\\omega$.',
          solution: '$a_t = (3.0)(0.25) = 0.75\\,\\mathrm{m/s}^2$. Nonzero because $\\alpha \\neq 0$.',
        },
        {
          id: 'hw-rk-1e',
          prompt: '(e) Radial acceleration of $P$ at $t = 2.0\\,\\mathrm{s}$.',
          kind: 'numeric',
          answer: 9,
          tolerance: 0.12,
          units: 'm/s²',
          hint: '$a_r = \\omega^2 R = v_t^2/R$.',
          solution: '$a_r = (6.0)^2(0.25) = 9.0\\,\\mathrm{m/s}^2$ toward the axis.',
        },
        {
          id: 'hw-rk-1f',
          prompt: '(f) At this instant the motion of $P$ is',
          kind: 'choice',
          answer: 'nonucm',
          choices: [
            { id: 'ucm', label: 'UCM, because $P$ travels on a circle of fixed $R$' },
            { id: 'nonucm', label: 'non-UCM: $a_t \\neq 0$ while $a_r$ is also present' },
            { id: 'none', label: 'neither circular nor accelerated, because the axis is fixed' },
            { id: 'trans', label: 'pure translation of the whole disk' },
          ],
          hint: 'A circular path is necessary but not sufficient for UCM. UCM also needs constant $|\\vec{v}|$.',
          solution:
            'Non-UCM. The path of $P$ is a circle, but $|\\vec{v}|$ is increasing. Both $a_r$ and $a_t$ appear on the rim-vector overlay. After a coast ($\\alpha = 0$ at this $\\omega$), the same $P$ would be in UCM.',
        },
      ],
    },
  ],
  'n2-cart': [
    {
      id: 'hw-n2-1',
      kind: 'multistep',
      title: 'Cart and hanger with kinetic friction',
      stem:
        'A cart $m_c = 1.50\\,\\mathrm{kg}$ on a horizontal track is connected by a light string over a light frictionless pulley to a hanging mass $m_h = 0.250\\,\\mathrm{kg}$. Kinetic friction acts on the cart with $\\mu_k = 0.10$. The hanger is descending. Take $g = 9.80\\,\\mathrm{m/s}^2$, and take the string inextensible.',
      figure: 'cart-hanger-friction',
      source: {
        credit: OPENSTAX + '. Structure follows connected-object examples in Chapter 6 (Atwood / cart and hanger).',
        url: 'https://openstax.org/books/university-physics-volume-1/pages/6-1-solving-problems-with-newtons-laws',
      },
      simSlug: 'newtons-second-law-cart',
      parts: [
        {
          id: 'hw-n2-1a',
          prompt: '(a) Magnitude of kinetic friction on the cart.',
          kind: 'numeric',
          answer: 1.47,
          tolerance: 0.06,
          units: 'N',
          hint: '$N = m_c g$ on the horizontal track. $f_k = \\mu_k N$.',
          solution: '$f_k = 0.10\\times 1.50\\times 9.80 = 1.47\\,\\mathrm{N}$.',
          simSlug: 'newtons-second-law-cart',
          simParams: { mCart: 1.5, mHanger: 0.25, frictionEnabled: true, muK: 0.1 },
        },
        {
          id: 'hw-n2-1b',
          prompt: '(b) Magnitude of the acceleration of the system.',
          kind: 'numeric',
          answer: 0.56,
          tolerance: 0.04,
          units: 'm/s²',
          hint: 'System: $m_h g - f_k = (m_c+m_h)a$. Tension cancels.',
          solution:
            '$a = (0.250\\times 9.80 - 1.47)/(1.50+0.250) = 0.980/1.75 = 0.560\\,\\mathrm{m/s}^2$.',
        },
        {
          id: 'hw-n2-1c',
          prompt: '(c) Tension in the string.',
          kind: 'numeric',
          answer: 2.31,
          tolerance: 0.08,
          units: 'N',
          hint: 'Hanger FBD: $m_h g - T = m_h a$, or cart: $T - f_k = m_c a$.',
          solution: '$T = m_h(g-a) = 0.250(9.80-0.560) = 2.31\\,\\mathrm{N}$. Check: $T = f_k + m_c a = 1.47 + 0.840 = 2.31\\,\\mathrm{N}$.',
        },
        {
          id: 'hw-n2-1d',
          prompt: '(d) Time for the cart to move $0.80\\,\\mathrm{m}$ from rest.',
          kind: 'numeric',
          answer: 1.69,
          tolerance: 0.08,
          units: 's',
          hint: '$\\Delta x = \\tfrac{1}{2}at^2$.',
          solution: '$t = \\sqrt{2(0.80)/0.560} = 1.69\\,\\mathrm{s}$.',
        },
      ],
    },
  ],
  n3: [
    {
      id: 'hw-n3-1',
      kind: 'multistep',
      title: 'Two blocks and a contact force',
      stem:
        'Blocks $m_1 = 2.0\\,\\mathrm{kg}$ and $m_2 = 3.0\\,\\mathrm{kg}$ rest on a frictionless horizontal surface and touch. A horizontal force of magnitude $F = 10\\,\\mathrm{N}$ is applied to $m_1$ as in the figure, so that $m_1$ pushes $m_2$. Let $F_{12}$ be the force of $m_1$ on $m_2$.',
      figure: 'two-blocks',
      source: {
        credit: OPENSTAX + '. Standard two-block contact example (Chapter 5–6).',
        url: 'https://openstax.org/books/university-physics-volume-1/pages/5-5-newtons-third-law',
      },
      simSlug: 'newtons-third-law',
      parts: [
        {
          id: 'hw-n3-1a',
          prompt: '(a) Acceleration of the two-block system.',
          kind: 'numeric',
          answer: 2,
          tolerance: 0.06,
          units: 'm/s²',
          hint: 'External horizontal force is only $F$. Contact forces are internal.',
          solution: '$a = F/(m_1+m_2) = 10/5.0 = 2.0\\,\\mathrm{m/s}^2$.',
          simSlug: 'newtons-third-law',
          simParams: { m1: 2, m2: 3, F_app: 10 },
        },
        {
          id: 'hw-n3-1b',
          prompt: '(b) Magnitude of the contact force on $m_2$.',
          kind: 'numeric',
          answer: 6,
          tolerance: 0.08,
          units: 'N',
          hint: 'Isolate $m_2$: $\\Sigma F = m_2 a$.',
          solution: '$F_{12} = m_2 a = 3.0\\times 2.0 = 6.0\\,\\mathrm{N}$.',
        },
        {
          id: 'hw-n3-1c',
          prompt:
            '(c) If instead $F$ is applied to $m_2$ (pushing the pair the other way), the contact force on $m_1$ is',
          kind: 'numeric',
          answer: 4,
          tolerance: 0.08,
          units: 'N',
          hint: 'Same $a$, but now isolate the other block: $F_\\mathrm{contact} = m_1 a$.',
          solution:
            '$a$ is still $2.0\\,\\mathrm{m/s}^2$. The contact force is now $m_1 a = 4.0\\,\\mathrm{N}$. Pair magnitudes are equal; which value you need depends on which mass you isolate.',
        },
        {
          id: 'hw-n3-1d',
          prompt: '(d) $|\\vec{F}_{12}|$ compared with $|\\vec{F}_{21}|$ while the system accelerates is',
          kind: 'choice',
          answer: 'equal',
          choices: [
            { id: 'larger', label: 'larger, because $m_1$ is “doing the pushing”' },
            { id: 'smaller', label: 'smaller, because $m_2$ is heavier' },
            { id: 'equal', label: 'equal at every instant (third-law pair)' },
            { id: 'unequal-a', label: 'unequal whenever $a \\neq 0$' },
          ],
          hint: 'Third-law pairs do not care which mass is larger or whether $a$ is zero.',
          solution:
            'Equal. $F$ is not the partner of $F_{12}$. Net force on each block can differ ($m_1$: $F-F_{21}$; $m_2$: $F_{12}$) while $|F_{12}|=|F_{21}|$.',
        },
      ],
    },
  ],
  friction: [
    {
      id: 'hw-fr-1',
      kind: 'multistep',
      title: 'Block on a rough incline',
      stem:
        'A $4.00\\,\\mathrm{kg}$ block is placed on a $30.0^\\circ$ incline. The coefficients are $\\mu_s = 0.40$ and $\\mu_k = 0.30$. Take $g = 9.80\\,\\mathrm{m/s}^2$. Decide first whether the block remains at rest; then, if it moves, find the acceleration down the plane. Keep three-significant-figure answers.',
      figure: 'incline-block',
      source: {
        credit: OPENSTAX + '. Follows §6.2 (friction) incline problems; numbers chosen for SN1.',
        url: 'https://openstax.org/books/university-physics-volume-1/pages/6-2-friction',
      },
      simSlug: 'friction',
      relatedCheckNote:
        'Related check: open the simulation to compare static vs kinetic friction on a horizontal surface (the incline figure is a paper problem).',
      simButtonLabel: 'Related check: compare $f_s$ and $f_k$',
      parts: [
        {
          id: 'hw-fr-1a',
          prompt: '(a) Component of weight down the plane, $mg\\sin\\theta$.',
          kind: 'numeric',
          answer: 19.6,
          tolerance: 0.15,
          units: 'N',
          hint: '$\\sin 30^\\circ = 1/2$.',
          solution: '$4.00\\times 9.80\\times 0.500 = 19.6\\,\\mathrm{N}$.',
        },
        {
          id: 'hw-fr-1b',
          prompt: '(b) Maximum static friction $\\mu_s N = \\mu_s mg\\cos\\theta$.',
          kind: 'numeric',
          answer: 13.6,
          tolerance: 0.2,
          units: 'N',
          hint: '$\\cos 30^\\circ = \\sqrt{3}/2 \\approx 0.866$.',
          solution: '$N = 4.00\\times 9.80\\times 0.866 = 33.9\\,\\mathrm{N}$, so $f_s^\\mathrm{max} = 0.40\\times 33.9 = 13.6\\,\\mathrm{N}$.',
        },
        {
          id: 'hw-fr-1c',
          prompt: '(c) Does the block remain at rest?',
          kind: 'choice',
          answer: 'slides',
          choices: [
            { id: 'rest', label: 'Yes; $mg\\sin\\theta \\le f_s^\\mathrm{max}$' },
            { id: 'slides', label: 'No; $mg\\sin\\theta > f_s^\\mathrm{max}$, so it slides' },
            { id: 'hang', label: 'It hangs in the air because $N = 0$' },
            { id: 'up', label: 'It accelerates up the plane' },
          ],
          hint: 'Compare (a) with (b). Static friction cannot exceed $\\mu_s N$.',
          solution: 'It slides. $19.6\\,\\mathrm{N} > 13.6\\,\\mathrm{N}$, so static friction cannot hold it.',
        },
        {
          id: 'hw-fr-1d',
          prompt: '(d) Acceleration down the plane once it is sliding.',
          kind: 'numeric',
          answer: 2.35,
          tolerance: 0.08,
          units: 'm/s²',
          hint: '$a = g(\\sin\\theta - \\mu_k\\cos\\theta)$.',
          solution:
            '$a = 9.80(0.500 - 0.30\\times 0.866) = 9.80(0.240) = 2.35\\,\\mathrm{m/s}^2$ down the plane.',
        },
      ],
    },
  ],
  'force-table': [
    {
      id: 'hw-ft-1',
      kind: 'multistep',
      title: 'Three strings on a force table',
      stem:
        'A light ring is in equilibrium under three horizontal strings. $\\vec{F}_1 = 8.0\\,\\mathrm{N}$ at $0^\\circ$ (along $+x$) and $\\vec{F}_2 = 6.0\\,\\mathrm{N}$ at $90^\\circ$ (along $+y$). Find the third force $\\vec{F}_3$ that the remaining string must exert. Report components in the usual $xy$ axes, then the magnitude. Angles are measured counterclockwise from $+x$.',
      figure: 'force-table-3',
      source: {
        credit: 'Original SN1 force-table lab problem (vector equilibrium).',
      },
      simSlug: 'force-table-equilibrium',
      parts: [
        {
          id: 'hw-ft-1a',
          prompt: '(a) $x$-component of $\\vec{F}_3$ required for $\\Sigma F_x = 0$.',
          kind: 'numeric',
          answer: -8,
          tolerance: 0.08,
          units: 'N',
          hint: '$F_{1x}+F_{2x}+F_{3x} = 0$.',
          solution: '$8.0 + 0 + F_{3x} = 0 \\Rightarrow F_{3x} = -8.0\\,\\mathrm{N}$.',
          simSlug: 'force-table-equilibrium',
          simParams: { activeCount: 3, f1: 8, a1: 0, f2: 6, a2: 90 },
        },
        {
          id: 'hw-ft-1b',
          prompt: '(b) $y$-component of $\\vec{F}_3$.',
          kind: 'numeric',
          answer: -6,
          tolerance: 0.08,
          units: 'N',
          hint: '$F_{2y} = 6.0\\,\\mathrm{N}$.',
          solution: '$0 + 6.0 + F_{3y} = 0 \\Rightarrow F_{3y} = -6.0\\,\\mathrm{N}$.',
        },
        {
          id: 'hw-ft-1c',
          prompt: '(c) Magnitude $|\\vec{F}_3|$.',
          kind: 'numeric',
          answer: 10,
          tolerance: 0.12,
          units: 'N',
          hint: '$|\\vec{F}_3| = \\sqrt{F_{3x}^2+F_{3y}^2}$.',
          solution: '$\\sqrt{(-8)^2+(-6)^2} = 10\\,\\mathrm{N}$. This is the equilibrant of $\\vec{F}_1+\\vec{F}_2$.',
        },
        {
          id: 'hw-ft-1d',
          prompt: '(d) Direction of $\\vec{F}_3$, as an angle in $[0,360)$ from $+x$.',
          kind: 'numeric',
          answer: 217,
          tolerance: 2,
          units: 'deg',
          hint: 'Third quadrant: $180^\\circ + \\tan^{-1}(6/8)$.',
          solution:
            '$\\theta = 180^\\circ + \\tan^{-1}(6/8) = 216.9^\\circ$ (about $217^\\circ$). Check on the force table: $F_3$ opposite the resultant of $F_1$ and $F_2$.',
        },
      ],
    },
  ],
  energy: [
    {
      id: 'hw-we-1',
      kind: 'multistep',
      title: 'Slide into a vertical loop',
      stem:
        'A bead of mass $m = 0.150\\,\\mathrm{kg}$ is released from rest on a frictionless track that feeds a vertical loop of radius $R = 0.40\\,\\mathrm{m}$. The release height measured from the bottom of the loop is $H = 5.00 R$. Take $U_g = 0$ at the bottom, and $g = 9.80\\,\\mathrm{m/s}^2$.',
      figure: 'loop-the-loop',
      source: {
        credit: OPENSTAX + '. Loop-the-loop energy analysis as in Example 8.7 (vertical circle) and related problems.',
        url: 'https://openstax.org/books/university-physics-volume-1/pages/8-5-conservation-of-energy',
      },
      simSlug: 'work-energy-track',
      relatedCheckNote:
        'Related check: open the simulation to compare mechanical energy exchange on a valley track (the vertical loop figure is a paper problem).',
      simButtonLabel: 'Related check: compare $K$ and $U_g$',
      parts: [
        {
          id: 'hw-we-1a',
          prompt: '(a) Speed at the bottom of the loop.',
          kind: 'numeric',
          answer: 6.26,
          tolerance: 0.12,
          units: 'm/s',
          hint: '$mgH = \\tfrac{1}{2}mv^2$ with $H = 5R$.',
          solution: '$v = \\sqrt{2g(5R)} = \\sqrt{10\\times 9.80\\times 0.40} = 6.26\\,\\mathrm{m/s}$.',
          simSlug: 'work-energy-track',
          simParams: { frictionEnabled: false },
          relatedCheckNote:
            'Related check: open the simulation to compare speed from energy conservation on a frictionless track (not a vertical loop).',
          simButtonLabel: 'Related check: compare speed from energy',
        },
        {
          id: 'hw-we-1b',
          prompt: '(b) Speed at the top of the loop.',
          kind: 'numeric',
          answer: 4.85,
          tolerance: 0.1,
          units: 'm/s',
          hint: 'Height $2R$ at the top. $mgH = \\tfrac{1}{2}mv_\\mathrm{top}^2 + mg(2R)$.',
          solution: '$v_\\mathrm{top} = \\sqrt{2g(H-2R)} = \\sqrt{2g(3R)} = \\sqrt{23.52} = 4.85\\,\\mathrm{m/s}$.',
        },
        {
          id: 'hw-we-1c',
          prompt: '(c) Normal force from the track on the bead at the top (toward the centre).',
          kind: 'numeric',
          answer: 7.35,
          tolerance: 0.2,
          units: 'N',
          hint: 'At the top, $n + mg = m v^2/R$.',
          solution:
            '$n = m(v_\\mathrm{top}^2/R - g) = 0.150(23.52/0.40 - 9.80) = 0.150(49.0) = 7.35\\,\\mathrm{N}$.',
        },
        {
          id: 'hw-we-1d',
          prompt: '(d) Minimum release height $H_\\mathrm{min}/R$ so the bead just stays in contact at the top ($n = 0$).',
          kind: 'numeric',
          answer: 2.5,
          tolerance: 0.08,
          units: '',
          hint: 'Need $v_\\mathrm{top}^2 \\ge gR$, plus $mgH = \\tfrac{1}{2}m(gR) + mg(2R)$.',
          solution:
            '$H_\\mathrm{min} = \\tfrac{5}{2}R$, so $H_\\mathrm{min}/R = 2.50$. (Here $H = 5R$ is safely above that.)',
        },
      ],
    },
  ],
  torque: [
    {
      id: 'hw-tx-1',
      kind: 'multistep',
      title: 'Solid disk unwinding a hanging mass',
      stem:
        'A uniform solid disk of mass $M = 4.00\\,\\mathrm{kg}$ and radius $R = 0.20\\,\\mathrm{m}$ is free to rotate about a fixed horizontal axis through its centre. A light string is wrapped around the rim and supports a hanging mass $m = 1.50\\,\\mathrm{kg}$. The string does not slip. Take $I_\\mathrm{disk} = \\tfrac{1}{2}MR^2$ and $g = 9.80\\,\\mathrm{m/s}^2$. The hanging mass is released from rest.',
      figure: 'disk-unwinding',
      source: {
        credit: OPENSTAX + '. Unwinding / yo-yo structure as in Example 10.7 and §10.7 problems.',
        url: 'https://openstax.org/books/university-physics-volume-1/pages/10-7-newtons-second-law-for-rotation',
      },
      simSlug: 'fixed-axis-rotation',
      relatedCheckNote:
        'Related check: open the simulation to compare moment of inertia $I$ for a solid disk (the unwinding hanging-mass figure is a paper problem).',
      simButtonLabel: 'Related check: compare $I$ for a solid disk',
      parts: [
        {
          id: 'hw-tx-1a',
          prompt: '(a) Moment of inertia of the disk about the given axis.',
          kind: 'numeric',
          answer: 0.08,
          tolerance: 0.004,
          units: 'kg·m²',
          hint: '$I = \\tfrac{1}{2}MR^2$.',
          solution: '$I = \\tfrac{1}{2}(4.00)(0.20)^2 = 0.080\\,\\mathrm{kg\\,m}^2$.',
          simSlug: 'fixed-axis-rotation',
          simParams: { preset: 'solid-disk' },
          relatedCheckNote:
            'Related check: open the simulation to compare $I$ for a solid disk (not the hanging-mass unwind setup).',
          simButtonLabel: 'Related check: compare $I$',
        },
        {
          id: 'hw-tx-1b',
          prompt: '(b) Downward acceleration of the hanging mass.',
          kind: 'numeric',
          answer: 4.2,
          tolerance: 0.08,
          units: 'm/s²',
          hint: '$a = \\alpha R$ (no slip). Combine $mg - T = ma$ with $TR = I\\alpha$.',
          solution:
            '$T = (I/R^2)a = \\tfrac{1}{2}M a$. Then $a = mg/(m + M/2) = 14.7/(1.50+2.00) = 4.20\\,\\mathrm{m/s}^2$.',
        },
        {
          id: 'hw-tx-1c',
          prompt: '(c) Angular acceleration of the disk.',
          kind: 'numeric',
          answer: 21,
          tolerance: 0.4,
          units: 'rad/s²',
          hint: '$\\alpha = a/R$.',
          solution: '$\\alpha = 4.20/0.20 = 21\\,\\mathrm{rad/s}^2$.',
        },
        {
          id: 'hw-tx-1d',
          prompt: '(d) Tension in the string.',
          kind: 'numeric',
          answer: 8.4,
          tolerance: 0.15,
          units: 'N',
          hint: '$T = m(g-a)$, or $T = I\\alpha/R$.',
          solution: '$T = 1.50(9.80-4.20) = 8.40\\,\\mathrm{N}$. Check: $T = 0.080\\times 21/0.20 = 8.40\\,\\mathrm{N}$.',
        },
      ],
    },
  ],
};
