/** Board-style worked solutions for multi-step homework. Shown after teacher unlock. */
export const teacherWriteups: Record<string, string[]> = {
  'hw-kg-1': [
    'Treat the motion as three successive intervals with constant acceleration on each. Sketch $v$–$t$: a rising line from the origin to $t=4.0\\,\\mathrm{s}$, a plateau for $6.0\\,\\mathrm{s}$, then a falling line to $v=0$. Displacement on each interval is the signed area under that piece of $v$–$t$.',
    '(a) From rest, $v_1 = a_1 t_1 = (2.0)(4.0) = 8.0\\,\\mathrm{m/s}$. That is the cruise speed.',
    '(b) $\\Delta x_1 = \\tfrac{1}{2}a_1 t_1^2 = \\tfrac{1}{2}(2.0)(16) = 16\\,\\mathrm{m}$. Equivalently, a triangle of base $4.0\\,\\mathrm{s}$ and height $8.0\\,\\mathrm{m/s}$.',
    '(c) $\\Delta x_2 = v_1 t_2 = (8.0)(6.0) = 48\\,\\mathrm{m}$.',
    '(d) $0 = 8.0 + (-3.0)t_3 \\Rightarrow t_3 = 8/3 = 2.67\\,\\mathrm{s}$.',
    '(e) Braking distance from $v^2 = v_0^2 + 2a\\Delta x$: $0 = 64 + 2(-3)\\Delta x_3 \\Rightarrow \\Delta x_3 = 10.67\\,\\mathrm{m}$. Total $x = 16 + 48 + 10.67 = 74.7\\,\\mathrm{m}$.',
    'Classroom check: the $v$–$t$ areas $16 + 48 + \\tfrac{1}{2}(2.67)(8) = 74.7\\,\\mathrm{m}$ match. Students who add times instead of areas, or who use $a=-3$ on the cruise, miss (c) or (e).',
  ],
  'hw-iv-1': [
    'Given $x(t) = 4t - t^2$ on $0\\le t\\le 5\\,\\mathrm{s}$ (SI). Instantaneous velocity is the derivative, not a secant, unless the interval is specified.',
    '$v(t) = dx/dt = 4 - 2t$ and $a = dv/dt = -2.0\\,\\mathrm{m/s}^2$ (constant). The $x$–$t$ graph is a downward parabola; $v$–$t$ is a straight line with slope $-2$.',
    '(a) $v(1) = 4-2 = 2.0\\,\\mathrm{m/s}$ (tangent at $t=1$).',
    '(b) At rest when $v=0$: $4-2t=0 \\Rightarrow t=2.0\\,\\mathrm{s}$. That is the vertex of $x(t)$.',
    '(c) $a=-2.0\\,\\mathrm{m/s}^2$ at every instant on the given interval.',
    '(d) $x(2)=8-4=4\\,\\mathrm{m}$, $x(0)=0$, so $v_\\mathrm{avg}=[x(2)-x(0)]/2 = 2.0\\,\\mathrm{m/s}$. Because $v(t)$ is linear, this equals $v$ at the midpoint $t=1\\,\\mathrm{s}$. That coincidence is not general.',
  ],
  'hw-cm-1': [
    'Model the crest as a particle in a vertical circle of radius $R=50\\,\\mathrm{m}$. At the top the centre is below the car, so $\\vec{a}_r$ is downward. Choose down as the positive radial direction.',
    'Radial (Newton) at the crest: $mg - n = m v^2/R$, or $n = m(g - v^2/R)$. The normal force is the apparent weight.',
    '(a) $a_r = v^2/R = 256/50 = 5.12\\,\\mathrm{m/s}^2$.',
    '(b) $n = 800(9.80-5.12) = 3.74\\times 10^3\\,\\mathrm{N}$, less than $mg=7.84\\times 10^3\\,\\mathrm{N}$.',
    '(c) Loss of contact when $n=0$: $v_\\mathrm{max}=\\sqrt{gR}=\\sqrt{490}=22.1\\,\\mathrm{m/s}$. Faster than that, $mg$ is not enough to supply the required $mv^2/R$.',
    '(d) $n < mg$ at a crest (you feel lighter) and $n > mg$ in a dip. A common error is to put $n$ and $mg$ in the wrong order, or to treat this as UCM with $a=0$ because “speed is constant for an instant.” Speed may be momentarily constant; the direction of $\\vec{v}$ is still changing.',
  ],
  'hw-rk-1': [
    'Fixed-axis kinematics for the wheel, then circular-motion kinematics for a rim point $P$. The graphs of $\\theta,\\omega,\\alpha$ do not depend on $R$; $v_t$, $a_r$, and $a_t$ do.',
    'From rest with constant $\\alpha=3.0\\,\\mathrm{rad/s}^2$: $\\omega=\\alpha t$ and $\\theta=\\tfrac{1}{2}\\alpha t^2$. At $t=2.0\\,\\mathrm{s}$, $\\omega=6.0\\,\\mathrm{rad/s}$ and $\\theta=6.0\\,\\mathrm{rad}$ (unwrapped).',
    'At $P$: $v_t=\\omega R=1.50\\,\\mathrm{m/s}$, $a_t=\\alpha R=0.75\\,\\mathrm{m/s}^2$ (independent of $\\omega$), $a_r=\\omega^2 R=9.0\\,\\mathrm{m/s}^2$ toward the axis. Then $|\\vec{a}|=\\sqrt{a_r^2+a_t^2}\\approx 9.03\\,\\mathrm{m/s}^2$.',
    'This is non-UCM: $P$ travels on a circle, but $|\\vec{v}|$ is increasing, so both $a_r$ and $a_t$ are present. UCM would require $\\alpha=0$ at this $\\omega$ (the Constant $\\omega$ profile, or the coast after spin-up). A circular path alone does not make the motion uniform.',
    'Board remark: doubling $R$ at fixed $\\alpha(t)$ leaves $\\omega(t)$ unchanged and doubles $v_t$, $a_t$, and $a_r$. That is the point of the rim-vector overlay on the rotational-kinematics sim.',
  ],
  'hw-n2-1': [
    'Two objects, one inextensible string, pulley light and frictionless. Draw a system FBD (cart + hanger) and an object FBD. Tension is internal to the system; kinetic friction on the cart is external.',
    'Along the track: $N=m_c g$ and $f_k=\\mu_k N=(0.10)(1.50)(9.80)=1.47\\,\\mathrm{N}$, opposing the motion (cart toward the pulley).',
    'System equation, positive in the direction the hanger descends: $m_h g - f_k = (m_c+m_h)a$. Then $a=(2.45-1.47)/1.75=0.560\\,\\mathrm{m/s}^2$.',
    'Hanger: $m_h g - T = m_h a \\Rightarrow T=m_h(g-a)=0.250(9.24)=2.31\\,\\mathrm{N}$. Cart check: $T-f_k=m_c a \\Rightarrow T=1.47+0.840=2.31\\,\\mathrm{N}$.',
    'From rest, $0.80=\\tfrac{1}{2}(0.560)t^2 \\Rightarrow t=\\sqrt{2.857}=1.69\\,\\mathrm{s}$.',
    'If friction is omitted, $a=m_h g/(m_c+m_h)=1.40\\,\\mathrm{m/s}^2$ and $T$ is too large. If someone uses $\\mu_k(m_c+m_h)g$, they have put friction on the hanger.',
  ],
  'hw-n3-1': [
    'Frictionless floor: the only external horizontal force on the two-block system is $F$. Contact forces $F_{12}$ and $F_{21}$ are an internal third-law pair and cancel in the system equation.',
    '(a) $a=F/(m_1+m_2)=10/5.0=2.0\\,\\mathrm{m/s}^2$ for both blocks (they stay in contact).',
    '(b) Isolate $m_2$: the only horizontal force on it is the contact force, so $F_{12}=m_2 a=6.0\\,\\mathrm{N}$. Isolate $m_1$ as a check: $F-F_{21}=m_1 a \\Rightarrow F_{21}=10-4=6.0\\,\\mathrm{N}$.',
    '(c) If $F$ is applied to $m_2$ instead, $a$ is unchanged but the contact force becomes $m_1 a=4.0\\,\\mathrm{N}$. The pair is still equal and opposite; the value you compute depends on which mass you isolate.',
    '(d) $|\\vec{F}_{12}|=|\\vec{F}_{21}|$ at every instant, including while $a\\neq 0$. $F$ is not the partner of $F_{12}$. Students who say “the heavier block pushes back harder” are mixing the pair with net force.',
  ],
  'hw-fr-1': [
    'Resolve weight on the incline: $mg\\sin\\theta$ down the plane, $mg\\cos\\theta$ into the plane. $N=mg\\cos\\theta$. Static friction at most $\\mu_s N$; if the block slides, replace with $\\mu_k N$ down-the-plane opposing velocity.',
    '(a) $mg\\sin 30^\\circ=4.00\\times 9.80\\times 0.500=19.6\\,\\mathrm{N}$.',
    '(b) $N=4.00\\times 9.80\\times\\sqrt{3}/2=33.9\\,\\mathrm{N}$, so $f_s^\\mathrm{max}=0.40\\times 33.9=13.6\\,\\mathrm{N}$.',
    '(c) Compare: $19.6>13.6$, so static friction cannot hold the block. It slides. (If the numbers were reversed, $f_s=mg\\sin\\theta$ and $a=0$.)',
    '(d) Sliding: $a=g(\\sin\\theta-\\mu_k\\cos\\theta)=9.80(0.500-0.30\\times 0.866)=2.35\\,\\mathrm{m/s}^2$ down the plane.',
    'Do not use $\\mu_s$ in the acceleration once it is moving. A frequent error is $a=g\\sin\\theta$ (no friction) or $a=g(\\sin\\theta-\\mu_s\\cos\\theta)$.',
  ],
  'hw-ft-1': [
    'Equilibrium of the ring: $\\sum\\vec{F}=\\vec{0}$. $\\vec{F}_3$ is the equilibrant of $\\vec{F}_1+\\vec{F}_2$, i.e. $\\vec{F}_3=-(\\vec{F}_1+\\vec{F}_2)$.',
    'Components: $F_{1x}=8.0\\,\\mathrm{N}$, $F_{1y}=0$; $F_{2x}=0$, $F_{2y}=6.0\\,\\mathrm{N}$. Then $F_{3x}=-8.0\\,\\mathrm{N}$ and $F_{3y}=-6.0\\,\\mathrm{N}$.',
    '$|\\vec{F}_3|=\\sqrt{64+36}=10\\,\\mathrm{N}$. Direction: third quadrant, $\\theta=180^\\circ+\\tan^{-1}(6/8)=216.9^\\circ$ from $+x$ (report $217^\\circ$).',
    'On the table, the third string should sit opposite the resultant of the first two (resultant of $F_1$ and $F_2$ is $10\\,\\mathrm{N}$ at $36.9^\\circ$). Mixing resultant with equilibrant is the usual lab mistake: same magnitude, $180^\\circ$ apart.',
  ],
  'hw-we-1': [
    'Frictionless track: mechanical energy of the bead–Earth system is constant. Set $U_g=0$ at the bottom. Release from rest at height $H=5R$.',
    'Bottom: $mgH=\\tfrac{1}{2}mv_b^2 \\Rightarrow v_b=\\sqrt{2gH}=\\sqrt{10 g R}=\\sqrt{39.2}=6.26\\,\\mathrm{m/s}$.',
    'Top of the loop, height $2R$: $mgH=\\tfrac{1}{2}mv_t^2+mg(2R) \\Rightarrow v_t=\\sqrt{2g(H-2R)}=\\sqrt{6gR}=4.85\\,\\mathrm{m/s}$.',
    'Radial Newton at the top (centre downward): $n+mg=m v_t^2/R$. Then $n=m(v_t^2/R-g)=0.150(58.8-9.80)=7.35\\,\\mathrm{N}$, from the track on the bead, toward the centre.',
    'Just staying in contact means $n=0$ at the top, so $v_t^2=gR$. Energy then gives $mgH_\\mathrm{min}=\\tfrac{1}{2}m(gR)+mg(2R) \\Rightarrow H_\\mathrm{min}=\\tfrac{5}{2}R$, or $H_\\mathrm{min}/R=2.50$. The given $H=5R$ is safely above that.',
    'Using $n=mv^2/R$ without $mg$, or taking the top height as $R$ instead of $2R$, are the usual slips.',
  ],
  'hw-tx-1': [
    'Disk about a fixed axis, $I=\\tfrac{1}{2}MR^2=\\tfrac{1}{2}(4.00)(0.040)=0.080\\,\\mathrm{kg\\,m}^2$. Light string, no slip: $a=\\alpha R$ and the same $T$ on disk and mass.',
    'Hanging mass (down positive): $mg-T=ma$. Disk: $\\tau=TR=I\\alpha$, so $T=(I/R^2)a=\\tfrac{1}{2}M a$.',
    'Eliminate $T$: $mg-\\tfrac{1}{2}Ma=ma \\Rightarrow a=mg/(m+M/2)=14.7/3.50=4.20\\,\\mathrm{m/s}^2$ downward. Then $\\alpha=a/R=21\\,\\mathrm{rad/s}^2$.',
    '$T=m(g-a)=1.50(5.60)=8.40\\,\\mathrm{N}$. Check: $T=I\\alpha/R=0.080\\times 21/0.20=8.40\\,\\mathrm{N}$.',
    'If the disk is treated as a point mass at the rim, $I=MR^2$ and $a$ is too small. If $T=mg$, the mass would not accelerate. The Atwood analogue is $m$ versus an effective mass $M/2$ for a solid disk.',
  ],
};
